# Generated by Django 5.1.3 on 2025-10-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0002_user_order_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
