# Generated by Django 5.1.3 on 2025-10-09 16:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "indexes": [
                    models.Index(fields=["name"], name="product_inv_name_762879_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("sku", models.CharField(blank=True, max_length=32, unique=True)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of items in stock"
                    ),
                ),
                ("image", models.URLField(blank=True, max_length=1024, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="Discount percentage (e.g., 10 for 10%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="product_inventory.category",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["price"], name="product_inv_price_246b25_idx"),
                    models.Index(
                        fields=["category"], name="product_inv_categor_2f61cb_idx"
                    ),
                    models.Index(
                        fields=["discount"], name="product_inv_discoun_020aec_idx"
                    ),
                ],
            },
        ),
    ]
