# Generated by Django 5.1.3 on 2025-10-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of items in stock"
            ),
        ),
    ]
