# Generated by Django 5.1.3 on 2025-10-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_inventory", "0002_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of items in stock", null=True
            ),
        ),
    ]
