# Generated by Django 5.1.3 on 2025-10-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
