# Generated by Django 5.1.3 on 2025-10-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0002_user_order_no"),
        ("cart", "0003_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="auth_api.user",
            ),
        ),
    ]
