# Generated by Django 5.1.3 on 2025-10-18 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_api", "0002_user_order_no"),
        ("cart", "0003_alter_cartitem_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_items", models.PositiveIntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("coupon_code", models.CharField(blank=True, max_length=50, null=True)),
                ("delivery_address", models.CharField(max_length=500)),
                ("delivery_date", models.CharField(max_length=500)),
                ("is_paid", models.BooleanField(default=False)),
                ("is_canceled", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("dispatched", "Dispatched"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                        ],
                        default="placed",
                        max_length=20,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="cart.cart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="auth_api.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cart"], name="order_order_cart_id_2e72a0_idx"
                    ),
                    models.Index(
                        fields=["user"], name="order_order_user_id_a7f1ea_idx"
                    ),
                ],
            },
        ),
    ]
