# Generated by Django 5.1.3 on 2025-10-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.AddField(
            model_name="order",
            name="pg_type",
            field=models.CharField(default="Placed", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
