# Generated by Django 5.1.3 on 2025-10-19 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cartitem_cart"),
        ("order", "0002_remove_order_total_items_remove_order_total_price_and_more"),
        ("product_inventory", "0003_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="cart.cart",
            ),
        ),
        migrations.CreateModel(
            name="OrderedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="order.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_inventory.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["order"], name="order_order_order_i_253b95_idx"
                    ),
                    models.Index(
                        fields=["product"], name="order_order_product_9d4736_idx"
                    ),
                ],
                "unique_together": {("order", "product")},
            },
        ),
    ]
